INSERT Into TEAMS (TEAMNAME) VALUES ('1.FC Koeln');
INSERT Into TEAMS (TEAMNAME) VALUES ('Borussia Dortmund');
INSERT Into TEAMS (TEAMNAME) VALUES ('Bayern Muenchen');
INSERT Into TEAMS (TEAMNAME) VALUES ('Vfb Stuttgart');
